name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y cmake

      - name: Configure
        run: |
          cmake -S . -B build-wiringpi

      - name: Build
        run: |
          cmake --build build-wiringpi

      - name: Install
        run: |
          sudo cmake --install build-wiringpi --prefix /usr
